/**
 * compileChartConfig — transforms a ChartConfig document into runtime ChartProps.
 *
 * This is the boundary between the declarative config world and the stateful
 * render world.  The chart engine (ChartCanvas) only knows about ChartProps;
 * the caller only needs to know about ChartConfig.
 *
 * The compiler is the only place that:
 *  - Resolves PaletteColor tokens to hex strings
 *  - Resolves ChartInterval tokens to millisecond values
 *  - Calls indicator calculation functions and passes their output downstream
 *
 * For the full pipeline (validate → normalize → compile) use buildChartPipeline.
 */

import { calcSMA, calcEMA, calcBollingerBands } from './indicators';
import {
  INTERVAL_MS,
  PALETTE,
  type ChartConfig,
  type OverlayConfig,
} from './config';
import { validateChartConfig } from './validate';
import { normalizeChartConfig } from './normalize';
import type { ChartProps, Candle, IndicatorLine, ShadedArea } from './types';

/** ChartProps without layout dimensions — those come from the container at runtime. */
export type CompiledChart = Omit<ChartProps, 'width' | 'height'>;

/**
 * Full pipeline: validate → normalize → compile.
 *
 * Prefer this over calling compileChartConfig directly. Throws a single error
 * listing all validation problems if the config is structurally invalid.
 *
 * ```ts
 * const compiled = buildChartPipeline(config, candles);
 * // <ChartCanvas {...compiled} width={w} height={h} />
 * ```
 */
export function buildChartPipeline(config: ChartConfig, data: Candle[]): CompiledChart {
  const result = validateChartConfig(config);
  if (!result.valid) {
    const lines = result.errors.map((e) => `  [${e.code}] ${e.path}: ${e.message}`);
    throw new Error(`Invalid ChartConfig:\n${lines.join('\n')}`);
  }
  return compileChartConfig(normalizeChartConfig(config), data);
}

/**
 * Compile a ChartConfig + raw candle data into ChartProps ready for ChartCanvas.
 *
 * @param config - A versioned ChartConfig document (e.g. generated by an LLM).
 * @param data   - Raw OHLC candles from the data provider.
 * @returns      CompiledChart — merge with { width, height } before passing to ChartCanvas.
 *
 * @throws If `config.version` is not '1'.
 */
export function compileChartConfig(
  config: ChartConfig,
  data: Candle[],
): CompiledChart {
  if (config.version !== '1') {
    throw new Error(
      `Unsupported ChartConfig version "${config.version}". Expected "1".`,
    );
  }

  // Each overlay may produce one or more IndicatorLine objects (Bollinger → 3).
  const indicators: IndicatorLine[] = config.overlays.flatMap((overlay) =>
    compileOverlay(overlay, data),
  );

  const shadedAreas: ShadedArea[] = config.shadedAreas.map((area) => ({
    fromId: area.fromOverlayId,
    toId: area.toOverlayId,
    color: PALETTE[area.color],
    opacity: area.opacity,
  }));

  const showRsiPanel = config.subPanels.some((p) => p.type === 'rsi');

  return {
    data,
    indicators,
    shadedAreas,
    intervalMs: INTERVAL_MS[config.interval],
    visibleDataPoints: Math.min(500, Math.max(10, config.viewport.visibleCandles)),
    theme: config.theme,
    showOhlcHud: config.hud.showOhlcHud,
    showRsiPanel,
    chartType: config.priceDisplay,
  };
}

// ─── Overlay compilation ──────────────────────────────────────────────────────

/**
 * Returns one IndicatorLine per overlay, except BollingerOverlay which returns
 * three (upper / lower / basis).  Returns an empty array when there is
 * insufficient data for the indicator's lookback period.
 */
function compileOverlay(overlay: OverlayConfig, data: Candle[]): IndicatorLine[] {
  switch (overlay.type) {
    case 'sma': {
      const line = calcSMA(data, overlay.params.period, overlay.id, PALETTE[overlay.color]);
      if (!line) return [];
      if (overlay.label) line.name = overlay.label;
      return [line];
    }

    case 'ema': {
      const line = calcEMA(data, overlay.params.period, overlay.id, PALETTE[overlay.color]);
      if (!line) return [];
      if (overlay.label) line.name = overlay.label;
      return [line];
    }

    case 'bollinger_bands': {
      const { bands, params } = overlay;
      const result = calcBollingerBands(data, params.period, params.stdDev, {
        upper: PALETTE[bands.upper.color],
        lower: PALETTE[bands.lower.color],
        basis: PALETTE[bands.basis.color],
      });
      if (!result) return [];
      return [
        { ...result.upper, id: bands.upper.id, name: bands.upper.label ?? result.upper.name },
        { ...result.lower, id: bands.lower.id, name: bands.lower.label ?? result.lower.name },
        { ...result.basis, id: bands.basis.id, name: bands.basis.label ?? result.basis.name },
      ];
    }

    case 'vwap': {
      // VWAP requires volume data — not yet available in the Candle type.
      // Returns an empty series so the config is accepted without crashing.
      // TODO: add `volume` to Candle and implement calcVWAP in indicators.ts.
      console.warn('VWAP overlay is not yet implemented; skipping.');
      return [];
    }
  }
}
